pipeline {
    agent {
        label 'AGENT-1'
    }

    environment {
        COURSE = 'jENKINS'
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    parameters{
        string(name: 'PERSON', defaultValue: 'Jenkins', description: 'Who Should I say Hello to?')
    }

    stages{
        stage('Build'){
            steps{
                sh """
                    echo "Hi from Build stage"
                """
            }

        }
        stage('Test'){
            steps{
                sh """
                    echo "Hi from Test stage"
                """
            }

        }
    }
}